package cz.davidstrnadel.aura.core

enum class DecisionColor {
    GREEN,
    YELLOW,
    RED,
    BLUE,
    GRAY
}

enum class PrivacyImpact {
    NONE,
    APP_METADATA,
    DEVICE_METADATA,
    USER_GRANTED_USAGE_METADATA,
    SENSITIVE_CONTENT_NOT_COLLECTED
}

enum class RoleCategory {
    CAMERA,
    MAPS_NAVIGATION,
    MESSAGING,
    BROWSER,
    KEYBOARD,
    LAUNCHER,
    DIALER,
    CONTACTS_PROVIDER,
    MEDIA_PROVIDER,
    PAYMENT_BANKING,
    ACCESSIBILITY_TOOL,
    DEVICE_MANAGEMENT,
    VPN_SECURITY_APP,
    OEM_TELEMETRY_SERVICE,
    SYSTEM_COMPONENT,
    UNKNOWN_UTILITY,
    UNKNOWN_SIDELOAD
}

enum class ProvenanceClass {
    AOSP_KNOWN,
    GOOGLE_KNOWN,
    OEM_SIGNED_SYSTEM,
    CARRIER_COMPONENT,
    THIRD_PARTY_PREINSTALL,
    PLAY_INSTALLED,
    FDROID_OR_OPEN_SOURCE,
    UNKNOWN_SIDELOAD,
    OPAQUE_PRIVILEGED,
    UNKNOWN
}

enum class EvidenceSource {
    PACKAGE_MANAGER,
    MANIFEST_PERMISSION,
    MANIFEST_COMPONENT,
    INTENT_FILTER,
    INSTALLER_SOURCE,
    SIGNING_CERT_DIGEST,
    SOURCE_PARTITION,
    SETTINGS_SNAPSHOT,
    USAGE_STATS_OPT_IN,
    KNOWN_PACKAGE_DATABASE,
    ROLE_RULE,
    PROVENANCE_RULE,
    DECISION_POLICY,
    TEST_FIXTURE,
    OFFLINE_APK_ANALYZER
}

enum class DefensiveFindingType {
    DEBUGGABLE_SENSITIVE_APP,
    BACKUP_ALLOWED_SENSITIVE_APP,
    CLEARTEXT_TRAFFIC_ALLOWED,
    UNPROTECTED_EXPORTED_COMPONENT
}

enum class DefensiveFindingSeverity {
    INFO,
    LOW,
    MEDIUM,
    HIGH
}

enum class DefensivePostureClass {
    NO_OBSERVED_WEAKNESS,
    REVIEW_RECOMMENDED,
    WEAK_DEFENSIVE_SURFACE
}

enum class RemediationScope {
    USER,
    EXPERT_AUDIT,
    ENTERPRISE_ADMIN,
    RESEARCH,
    NONE
}

enum class EvidenceGraphNodeType {
    APP,
    EVIDENCE,
    ROLE,
    PROVENANCE,
    RISK_VECTOR,
    DECISION,
    RECOMMENDED_ACTION
}

enum class EvidenceGraphRelation {
    OBSERVED_FOR,
    SUPPORTS,
    CONTRADICTS,
    DERIVES,
    RECOMMENDS
}
